"""Static dashboard exporter.

The live dashboard is a React client backed by a local Fastify API.  GitHub
Pages can only serve files, so static export snapshots the API responses the
client needs and installs a tiny runtime fetch adapter that reads those JSON
files instead of calling ``/api/*``.
"""

from __future__ import annotations

import base64
import json
import shutil
import tempfile
import time
import urllib.error
import urllib.parse
import urllib.request
from collections import deque
from importlib import resources
from pathlib import Path
from typing import Any

import typer

from archon import log

from .build import build_client, check_node, install_if_needed
from .pidfile import PidFileRegistry
from .port import find_free_port
from .server import ServerProcess


MARKER = ".archon-static-dashboard"
_NO_PROXY_OPENER = urllib.request.build_opener(urllib.request.ProxyHandler({}))
PAGES_WORKFLOW = "archon-dashboard-pages.yml"


def _data_path(sub_path: str = "") -> Path:
    root = resources.files("archon")
    if sub_path:
        return Path(str(root.joinpath(sub_path)))
    return Path(str(root))


def _api_key(endpoint: str) -> str:
    raw = base64.urlsafe_b64encode(endpoint.encode("utf-8")).decode("ascii")
    return raw.rstrip("=")


def _quote_path(path: str) -> str:
    return urllib.parse.quote(path, safe="/._-")


def _fetch_json(base_url: str, endpoint: str, *, timeout: float = 90.0) -> Any | None:
    url = f"{base_url}{endpoint}"
    try:
        with _NO_PROXY_OPENER.open(url, timeout=timeout) as resp:
            raw = resp.read()
    except urllib.error.HTTPError:
        return None
    except (urllib.error.URLError, TimeoutError, OSError):
        return None
    if not raw:
        return None
    try:
        return json.loads(raw.decode("utf-8"))
    except json.JSONDecodeError:
        return None


def _write_json(out_dir: Path, endpoint: str, data: Any) -> None:
    target = out_dir / "data" / "api" / f"{_api_key(endpoint)}.json"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


class StaticDashboardExporter:
    def __init__(
        self,
        project_path: Path,
        *,
        out_dir: Path,
        port: int = 8090,
        force: bool = False,
    ) -> None:
        self.project_path = project_path.resolve()
        self.out_dir = out_dir.resolve()
        self.port = port
        self.force = force
        self.endpoints: set[str] = set()
        self.saved = 0

    def run(self) -> None:
        archon_dir = self.project_path / ".archon"
        if not archon_dir.is_dir():
            log.error(f"No .archon/ directory found in {self.project_path}")
            log.step("Run: archon init first, or check the project path")
            raise typer.Exit(1)

        ui_dir = _data_path("ui")
        server_dir = ui_dir / "server"
        client_dir = ui_dir / "client"
        if not ui_dir.exists():
            log.error("UI files not found in package data — installation may be incomplete")
            raise typer.Exit(1)

        self._prepare_output_dir()

        check_node()
        install_if_needed(server_dir, "server")
        install_if_needed(client_dir, "client")

        with tempfile.TemporaryDirectory(prefix="archon-dashboard-static-") as td:
            client_build = Path(td) / "client"
            log.step("Building static dashboard client...")
            build_client(client_dir, out_dir=client_build, base="./")
            shutil.copytree(client_build, self.out_dir, dirs_exist_ok=True)

        server = self._start_api_server(server_dir, archon_dir)
        try:
            self._snapshot_api(f"http://127.0.0.1:{server.port}")
        finally:
            server.cleanup()

        self._write_static_config()
        self._ensure_pages_workflow()
        (self.out_dir / MARKER).write_text(
            "Generated by archon dashboard --static-build\n",
            encoding="utf-8",
        )
        log.success(f"Static dashboard written to {self.out_dir}")
        log.info(f"Snapshotted {self.saved} API endpoints")
        log.step("GitHub Pages workflow is ready. In Settings → Pages, select GitHub Actions.")

    def _prepare_output_dir(self) -> None:
        if not self.out_dir.exists():
            self.out_dir.mkdir(parents=True)
            return
        entries = list(self.out_dir.iterdir())
        if entries and not (self.out_dir / MARKER).exists() and not self.force:
            log.error(f"Output directory is not empty: {self.out_dir}")
            log.step("Pass --force to replace it, or choose a different --out directory.")
            raise typer.Exit(1)
        shutil.rmtree(self.out_dir)
        self.out_dir.mkdir(parents=True)

    def _start_api_server(self, server_dir: Path, archon_dir: Path) -> ServerProcess:
        requested = self.port
        free = find_free_port(requested) or requested
        registry = PidFileRegistry(self.out_dir / ".tmp-ui", self.project_path)
        server = ServerProcess(
            server_dir=server_dir,
            project_path=self.project_path,
            archon_dir=archon_dir,
            registry=registry,
        )
        port = server.start_with_retry(free)
        log.step(f"Snapshotting dashboard API on http://127.0.0.1:{port}")
        return server

    def _enqueue(self, queue: deque[str], endpoint: str) -> None:
        if endpoint not in self.endpoints:
            self.endpoints.add(endpoint)
            queue.append(endpoint)

    def _snapshot_api(self, base_url: str) -> None:
        queue: deque[str] = deque()
        for endpoint in [
            "/api/project",
            "/api/progress",
            "/api/strategy",
            "/api/tasks",
            "/api/sorry-count",
            "/api/task-results",
            "/api/summary",
            "/api/journal/sessions",
            "/api/journal/all-milestones",
            "/api/journal/status",
            "/api/to-user",
            "/api/git/log",
            "/api/git/head",
            "/api/dag",
            "/api/dag/last-modified",
            "/api/blueprint/chapters",
            "/api/multilane",
            "/api/scope",
        ]:
            self._enqueue(queue, endpoint)

        while queue:
            endpoint = queue.popleft()
            timeout = 300.0 if self._slow_endpoint(endpoint) else 90.0
            data = self._cached_endpoint(endpoint)
            if data is None:
                data = _fetch_json(base_url, endpoint, timeout=timeout)
            if data is None:
                if self._important_endpoint(endpoint):
                    log.warn(f"Static export skipped slow or unavailable endpoint: {endpoint}")
                continue
            _write_json(self.out_dir, endpoint, data)
            self.saved += 1
            self._expand_endpoint(queue, endpoint, data)

    def _cached_endpoint(self, endpoint: str) -> Any | None:
        if endpoint == "/api/dag":
            cache = self.project_path / ".leandag" / "dag.json"
            if not cache.exists():
                return None
            try:
                raw = json.loads(cache.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                return None
            return {
                "nodes": raw.get("nodes") or [],
                "edges": raw.get("edges") or [],
                "meta": raw.get("meta") or {},
                "error": None,
            }
        if endpoint == "/api/dag/last-modified":
            return {"files": {}}
        return None

    def _slow_endpoint(self, endpoint: str) -> bool:
        path = endpoint.split("?", 1)[0]
        return (
            path == "/api/dag"
            or path.startswith("/api/proofgraph/")
            or path.startswith("/api/snapshot-files/")
            or "/snapshots/" in path
        )

    def _important_endpoint(self, endpoint: str) -> bool:
        path = endpoint.split("?", 1)[0]
        return path in {
            "/api/project",
            "/api/progress",
            "/api/dag",
            "/api/blueprint/chapters",
            "/api/git/log",
            "/api/git/head",
        }

    def _expand_endpoint(self, queue: deque[str], endpoint: str, data: Any) -> None:
        if endpoint == "/api/journal/sessions" and isinstance(data, list):
            for item in data:
                if isinstance(item, dict) and isinstance(item.get("id"), str):
                    sid = _quote_path(item["id"])
                    self._enqueue(queue, f"/api/journal/sessions/{sid}/milestones")
                    self._enqueue(queue, f"/api/journal/sessions/{sid}/summary")
                    self._enqueue(queue, f"/api/journal/sessions/{sid}/recommendations")
            return

    def _ensure_pages_workflow(self) -> None:
        workflows_dir = self.project_path / ".github" / "workflows"
        workflow_path = workflows_dir / PAGES_WORKFLOW
        if workflow_path.exists():
            log.info(f"GitHub Pages workflow already exists: {workflow_path}")
            return

        try:
            upload_path = self.out_dir.relative_to(self.project_path).as_posix()
        except ValueError:
            log.warn(
                "Static output is outside the project; skipping GitHub Pages workflow generation."
            )
            return

        workflows_dir.mkdir(parents=True, exist_ok=True)
        workflow_path.write_text(_pages_workflow(upload_path), encoding="utf-8")
        log.success(f"GitHub Pages workflow written to {workflow_path}")

    def _write_static_config(self) -> None:
        config = {
            "generatedAt": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "projectPath": str(self.project_path),
            "endpointCount": self.saved,
        }
        script = "window.__ARCHON_STATIC__ = " + json.dumps(config, ensure_ascii=False) + ";\n"
        (self.out_dir / "archon-static-config.js").write_text(script, encoding="utf-8")

        index = self.out_dir / "index.html"
        html = index.read_text(encoding="utf-8")
        tag = '<script src="./archon-static-config.js"></script>'
        if tag not in html:
            html = html.replace('<script type="module"', f'{tag}\n    <script type="module"', 1)
        index.write_text(html, encoding="utf-8")


def _pages_workflow(upload_path: str) -> str:
    return f"""name: Deploy Archon dashboard

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{{{ steps.deployment.outputs.page_url }}}}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: false

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload dashboard
        uses: actions/upload-pages-artifact@v4
        with:
          path: {json.dumps(upload_path)}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
"""
